.test-template:
  stage: unit-test
  image: $CI_REGISTRY_IMAGE_TEST:8.1
  variables:
    DOCKER_HOST: tcp://localhost:2376/
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:20.10.16-dind
  script:
    - apt-get update
    - apt-get install -y ca-certificates curl gnupg lsb-release
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install -y docker-ce-cli
    - cp config/app.default.php config/app.php
    - composer install --no-interaction
    - gpg --import config/gpg/unsecure_private.key
    - gpg --import config/gpg/unsecure.key
    - ./bin/cake passbolt create_jwt_keys
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - bin/paratest -d $CI_REGISTRY_IMAGE_TEST:$PHP_VERSION -p $DATABASE_ENGINE_VERSION
##
## CUSTOM COMBINATIONS
##
php7.4-mysql5.7:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mysql-5.7'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null'

# TO BE REMOVED
php7.4-postgres:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/postgres-12.2-alpine:latest'
  extends:
    - .test-template

##
## DEBIAN COMBINATIONS
##
## DEBIAN 10 BUSTER
php7.3-mariadb10.3:
  variables:
    PHP_VERSION: "7.3"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mariadb-10.3'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null'

## DEBIAN 11 BULLSEYE
php7.4-mariadb10.5:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mariadb-10.5'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "master"'
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "develop"'

## UBUNTU 20.04 LTS FOCAL
php7.4-mysql8:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mysql-8.0'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null'

## UBUNTU 22.04 LTS JAMMY
php8.1-mysql8:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mysql-8.0'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null'

##
## RPM COMBINATIONS
##
## CENTOS 7 - with remi and mariadb repos
php7.4-mariadb10.3:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mariadb-10.3'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "master"'
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "develop"'

## ROCKY LINUX 8.6
php8.0-mariadb10.5:
  variables:
    PHP_VERSION: "8.0"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mariadb-10.5'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "master"'
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "develop"'

## RHEL 9
php8.0-mariadb8.0:
  variables:
    PHP_VERSION: "8.0"
    DATABASE_ENGINE_VERSION: '$CI_REGISTRY/mysql-8.0'
  extends:
    - .test-template
  rules:
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "master"'
    - if: '$TEST_DISABLED == null && $CI_COMMIT_BRANCH == "develop"'
